newIssueWelcomeComment: >
  Thanks for opening your first issue here!
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
firstPRMergeComment: |
  Congrats on merging your first pull request! We here are proud of you! ğŸ‰ğŸ‰ğŸ‰ğŸ‰.